modules:
    base:
        dialogue:
            path: processors/dialogue
#        emotion:
#            path: processors/emotion
#        memory:
#            path: processors/memory
    system:
        qq:
            value: false
            path: modules/system/qq
        example:
            value: false
            path: modules/system/example
    user:
        example:
            value: false
            path: modules/user/example